import payload from "@/data/repro.json";
import { PipelineChecks } from "@/components/pipelinechecks";

interface Step {
  label: string;
  command: string;
  seconds: number;
  exit_code: number;
}

interface Repro {
  machine: { python: string; platform: string; processor: string };
  steps: Step[];
  total_seconds: number;
  dollars: number;
}

const repro = payload as unknown as Repro;

export default function ReproducePage() {
  return (
    <main>
      <h1>Reproduce this</h1>
      <p className="lede">
        Written for someone starting from a clean machine. Every figure on this site comes from the
        three commands below, and running them regenerates the corpus, the report data and the
        comparison from scratch. No key, no account and no network call is involved.
      </p>

      <h2 className="ruled">It runs on every pull request</h2>
      <p className="lede short">
        The same commands run in CI, so the claim on this site is checked against the code on every
        change rather than on the day it was written. The job is
        <code> .github/workflows/shakedown.yml</code>.
      </p>
      <PipelineChecks />

      <h2>What you need</h2>
      <table className="plain">
        <tbody>
          <tr>
            <td>Python</td>
            <td>{repro.machine.python} or newer, standard library only</td>
          </tr>
          <tr>
            <td>Node</td>
            <td>20 or newer, only if you want to view the site</td>
          </tr>
          <tr>
            <td>Measured on</td>
            <td>{repro.machine.platform}</td>
          </tr>
          <tr>
            <td>Data required</td>
            <td>None. The corpus is generated by the first command from a seed.</td>
          </tr>
        </tbody>
      </table>

      <h2>The three commands</h2>
      <p className="lede">
        Run these from the root of the repository. The seed is the third argument to the generator,
        and the same seed always produces the same corpus byte for byte.
      </p>
      <table className="plain">
        <thead>
          <tr>
            <th>Step</th>
            <th>Command</th>
            <th>Measured</th>
          </tr>
        </thead>
        <tbody>
          {repro.steps.map((step) => (
            <tr key={step.label}>
              <td>{step.label}</td>
              <td>
                <code>{step.command}</code>
              </td>
              <td>{step.seconds.toFixed(1)}s</td>
            </tr>
          ))}
          <tr>
            <td>
              <strong>Total</strong>
            </td>
            <td>End to end from a clean checkout</td>
            <td>
              <strong>{repro.total_seconds.toFixed(0)}s</strong>
            </td>
          </tr>
        </tbody>
      </table>

      <h2>What you should see</h2>
      <p className="lede">
        The generator writes 24 bundles and a label file, and stops with a named bundle if any
        planted defect fails to manifest. The gauntlet prints one line per bundle with its verdict
        and finishes by writing the report file. The comparison prints both arms side by side and
        ends with the headline, which on this machine reads that the hand checks caught 6 of 21
        planted defects and the gauntlet caught 13 of 21.
      </p>

      <h2>Cost</h2>
      <p className="lede">
        {repro.dollars.toFixed(2)} dollars. Every probe reaches its verdict by executing the bundle
        rather than by asking a model, so reproducing the numbers costs nothing beyond the {repro.total_seconds.toFixed(0)} seconds
        of compute above.
      </p>

      <h2>Viewing the site</h2>
      <p className="lede">
        From the <code>site</code> directory run <code>npm install</code> and then{" "}
        <code>npm run build</code>. The build writes a static export to <code>site/out</code>, which
        any static server can host and which needs no running backend.
      </p>
    </main>
  );
}
